spring:
  data:
    cassandra:
      keyspace-name: report
      contact-points: localhost

worker:
     - chunkSize: 100
       requestTimeoutMs: 30000

teamcity:
     servers:
            - name: Local Team City
              apiVersion: latest
              url: http://localhost:8111
              username: admin
              password: 123456 # TODO encrypt
