spring:
  data:
    cassandra:
      keyspace-name: report
      contact-points: localhost

teamcity:
     servers:
            - name: Local Team City
              apiVersion: latest
              url: http://localhost:8111
              username: admin
              password: 123456 # TODO encrypt
              worker:
                    actualizationDays: 1
                    chunkSize: 100
                    requestTimeoutMs: 2000
                    startPage: 0
