server:
  port: ${ui.app.server.port:8080}
spring:
 data:
     cassandra:
       keyspace-name: ${cassandra.keyspace:report}
       contact-points: ${cassandra.host}
       port: ${cassandra.port:9042}
       username: ${cassandra.username:}
       password: ${cassandra.password:}
vaadin:
  servlet:
    production-mode: ${vaadin.production.mode:true}