server:
  port: ${indexer.app.server.port:8080}
spring:
  batch:
    job:
      enabled: false
  data:
    cassandra:
      keyspace-name: ${cassandra.keyspace:report}
      contact-points: ${cassandra.host}
      port: ${cassandra.port:9042}
      username: ${cassandra.username:}
      password: ${cassandra.password:}

teamcity:
     servers:
            - id: ${teamcity.server.id}
              name: ${teamcity.server.name}
              apiVersion: ${teamcity.server.apiVersion:latest}
              url: ${teamcity.server.url}
              username: ${teamcity.server.username:}
              password: ${teamcity.server.password:}
              worker:
                    actualizationDays: ${teamcity.server.actualizationDays:1}
                    chunkSize: ${teamcity.server.chunkSize:100}
                    commitInterval: ${teamcity.server.commitInterval:1}
                    requestTimeoutMs: ${teamcity.server.requestTimeoutMs:10000}
                    startPage: ${teamcity.server.startPage:0}
