server:
  port: 8222
spring:
  batch:
    job:
      enabled: false
  data:
    cassandra:
      keyspace-name: report
      contact-points: localhost

teamcity:
     servers:
            - id: LocalTC
              name: Local TeamCity
              apiVersion: latest
              url: http://localhost:8111
              username: admin
              password: 123456
              worker:
                    actualizationDays: 1
                    chunkSize: 100
                    requestTimeoutMs: 2000
                    startPage: 0
